[Settings]
  ID = "044a6266-766e-4756-a05a-4f2d3223e68e"

[build]
  command = "bun run build"
  functions = "netlify/functions"
  publish = "_site"

# Form handling configuration
[form]
  enabled = true

[[redirects]]
  from = "/success"
  to = "/#signup"
  status = 200
  force = false

[[redirects]]
  from = "/success-impact"
  to = "/#impact"
  status = 200
  force = false


[[redirects]]
  from = "/"
  to = "https://www.instagram.com/omahasoundry"
  status = 301
  force = true
